// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teltonika.DataModels;
using Teltonika.DBContext;

namespace Teltonika.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220425203543_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Teltonika.DataModels.Covid19Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("object_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgeBracket")
                        .HasColumnName("age_bracket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseCode")
                        .HasColumnName("case_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ConfimationDate")
                        .HasColumnName("confirmation_date")
                        .HasColumnType("datetimeoffset");

                    b.Property<float?>("CoordinateX")
                        .HasColumnName("X")
                        .HasColumnType("real");

                    b.Property<float?>("CoordinateY")
                        .HasColumnName("Y")
                        .HasColumnType("real");

                    b.Property<string>("Gender")
                        .HasColumnName("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MunicipalityCode")
                        .HasColumnName("municipality_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MunicipalityName")
                        .HasColumnName("municipality_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Covid19Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
